# version: '3.8'

services:
  consul:
    image: consul:1.10.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    ports:
      - '4000:4000'
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  auth-service:
    build: ./auth-service
    ports:
      - '5010:5010'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  merchant-service:
    build: ./merchant-service
    ports:
      - '5002:5002'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/merchant_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  notification-service:
    build: ./notification-service
    ports:
      - '5003:5003'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notification_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=ae.elhamiani@gmail.com
      - SMTP_PASS=ehci khce cibu dfwi
    depends_on:
      consul:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  otp-service:
    build: ./otp-service
    ports:
      - '5004:5004'
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  store-service:
    build: ./store-service
    ports:
      - '5005:5005'
    depends_on:
      consul:
        condition: service_healthy
      graph-node:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    

  payment-service:
    build: ./payment-service
    ports:
      - '5006:5006'
    depends_on:
      consul:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      PAYMENT_SERVICE_URL: http://payment-service:5006/graphql
      GWEPAY_FRONTEND_HOST: http://host.docker.internal
      GWEPAY_FRONTEND_PORT: 5173

    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content/plugins/gwepay-payment-gateway:/var/www/html/wp-content/plugins/gwepay-payment-gateway
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - wordpress_db


  wordpress_db:
    image: mysql:8.0
    volumes:
      - wordpress_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'localhost:http://host.docker.internal:8545' # Updated to include the network name
      GRAPH_LOG: info

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh


volumes:
  mongodb_data:
  redis_data:
  postgres_data:
  wordpress_data:
  wordpress_db_data:

networks:
  myapp-network:
    name: myapp-network,
