# version: '3.8'

services:
  consul:
    image: consul:1.10.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    ports:
      - '4000:4000'
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  auth-service:
    build: ./auth-service
    ports:
      - '5001:5001'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  merchant-service:
    build: ./merchant-service
    ports:
      - '5002:5002'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/merchant_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      consul:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  notification-service:
    build: ./notification-service
    ports:
      - '5003:5003'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notification_db
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=ae.elhamiani@gmail.com
      - SMTP_PASS=ehci khce cibu dfwi
    depends_on:
      consul:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  otp-service:
    build: ./otp-service
    ports:
      - '5004:5004'
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  store-service:
    build: ./store-service
    ports:
      - '5005:5005'
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  payment-service:
    build: ./store-service
    ports:
      - '5006:5006'
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      PAYMENT_SERVICE_URL: 
      AUTH_SERVICE_URL: 
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content/plugins/gwepay-payment-gateway:/var/www/html/wp-content/plugins/gwepay-payment-gateway
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php

    depends_on:
      - wordpress_db
    networks:
      - myapp-network

  wordpress_db:
    image: mysql:8.0
    volumes:
      - wordpress_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    networks:
      - myapp-network

volumes:
  mongodb_data:
  redis_data:
  wordpress_data:
  wordpress_db_data:

networks:
  myapp-network:
    name: myapp-network
